// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: shipping.proto

package shipping

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeliveryItem represents an item to be delivered.
type DeliveryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryItem) Reset() {
	*x = DeliveryItem{}
	mi := &file_shipping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryItem) ProtoMessage() {}

func (x *DeliveryItem) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryItem.ProtoReflect.Descriptor instead.
func (*DeliveryItem) Descriptor() ([]byte, []int) {
	return file_shipping_proto_rawDescGZIP(), []int{0}
}

func (x *DeliveryItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *DeliveryItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// ShippingRequest is the request message for the Shipping service.
type ShippingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DeliveryItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	PurchaseId    string                 `protobuf:"bytes,2,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingRequest) Reset() {
	*x = ShippingRequest{}
	mi := &file_shipping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingRequest) ProtoMessage() {}

func (x *ShippingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingRequest.ProtoReflect.Descriptor instead.
func (*ShippingRequest) Descriptor() ([]byte, []int) {
	return file_shipping_proto_rawDescGZIP(), []int{1}
}

func (x *ShippingRequest) GetItems() []*DeliveryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ShippingRequest) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

// ShippingResponse is the response message containing the delivery time.
type ShippingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryTime  string                 `protobuf:"bytes,1,opt,name=delivery_time,json=deliveryTime,proto3" json:"delivery_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingResponse) Reset() {
	*x = ShippingResponse{}
	mi := &file_shipping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingResponse) ProtoMessage() {}

func (x *ShippingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingResponse.ProtoReflect.Descriptor instead.
func (*ShippingResponse) Descriptor() ([]byte, []int) {
	return file_shipping_proto_rawDescGZIP(), []int{2}
}

func (x *ShippingResponse) GetDeliveryTime() string {
	if x != nil {
		return x.DeliveryTime
	}
	return ""
}

var File_shipping_proto protoreflect.FileDescriptor

const file_shipping_proto_rawDesc = "" +
	"\n" +
	"\x0eshipping.proto\"C\n" +
	"\fDeliveryItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"W\n" +
	"\x0fShippingRequest\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.DeliveryItemR\x05items\x12\x1f\n" +
	"\vpurchase_id\x18\x02 \x01(\tR\n" +
	"purchaseId\"7\n" +
	"\x10ShippingResponse\x12#\n" +
	"\rdelivery_time\x18\x01 \x01(\tR\fdeliveryTime2O\n" +
	"\x0fShippingService\x12<\n" +
	"\x15CalculateDeliveryTime\x12\x10.ShippingRequest\x1a\x11.ShippingResponseB@Z>github.com/gabrielmacaubas/microservices-proto/golang/shippingb\x06proto3"

var (
	file_shipping_proto_rawDescOnce sync.Once
	file_shipping_proto_rawDescData []byte
)

func file_shipping_proto_rawDescGZIP() []byte {
	file_shipping_proto_rawDescOnce.Do(func() {
		file_shipping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipping_proto_rawDesc), len(file_shipping_proto_rawDesc)))
	})
	return file_shipping_proto_rawDescData
}

var file_shipping_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shipping_proto_goTypes = []any{
	(*DeliveryItem)(nil),     // 0: DeliveryItem
	(*ShippingRequest)(nil),  // 1: ShippingRequest
	(*ShippingResponse)(nil), // 2: ShippingResponse
}
var file_shipping_proto_depIdxs = []int32{
	0, // 0: ShippingRequest.items:type_name -> DeliveryItem
	1, // 1: ShippingService.CalculateDeliveryTime:input_type -> ShippingRequest
	2, // 2: ShippingService.CalculateDeliveryTime:output_type -> ShippingResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shipping_proto_init() }
func file_shipping_proto_init() {
	if File_shipping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipping_proto_rawDesc), len(file_shipping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipping_proto_goTypes,
		DependencyIndexes: file_shipping_proto_depIdxs,
		MessageInfos:      file_shipping_proto_msgTypes,
	}.Build()
	File_shipping_proto = out.File
	file_shipping_proto_goTypes = nil
	file_shipping_proto_depIdxs = nil
}